In [1]:
import numpy as np
import pandas as pd

In [2]:
range_array = np.arange(0, 10, 2)
range_array

array([0, 2, 4, 6, 8])

In [3]:
random_array = np.random.randint(0, 10, size=(3, 5))
random_array

array([[7, 2, 5, 4, 8],
       [8, 4, 4, 4, 4],
       [6, 0, 2, 4, 9]])

In [4]:
random_array.size

15

In [5]:
random_array.shape

(3, 5)

In [11]:
random_array_2 = np.random.random((5, 3))
random_array_2

array([[0.20484909, 0.49076589, 0.37238469],
       [0.47740115, 0.36589039, 0.83791799],
       [0.76864751, 0.31399468, 0.57262533],
       [0.27604905, 0.45284293, 0.35297837],
       [0.65739946, 0.37035108, 0.45909298]])

In [12]:
random_array_3 = np.random.rand(5, 3)
random_array_3

array([[0.71932412, 0.41299183, 0.90642327],
       [0.18045162, 0.74111887, 0.42237404],
       [0.42645357, 0.63437987, 0.5229062 ],
       [0.41488598, 0.00142688, 0.09226235],
       [0.70939439, 0.5243456 , 0.69616046]])

In [13]:
# Pseudo-random numbers
np.random.seed(seed=99999) # seed 0 olursa sayılar hiç değişmez
random_array_4 = np.random.randint(10, size=(5, 3))
random_array_4

array([[0, 3, 1],
       [8, 1, 3],
       [8, 5, 6],
       [0, 6, 0],
       [4, 0, 9]])

In [21]:
np.random.seed(7)
random_array_5 = np.random.random((5, 3))
random_array_5

array([[0.07630829, 0.77991879, 0.43840923],
       [0.72346518, 0.97798951, 0.53849587],
       [0.50112046, 0.07205113, 0.26843898],
       [0.4998825 , 0.67923   , 0.80373904],
       [0.38094113, 0.06593635, 0.2881456 ]])

In [19]:
random_array_5 = np.random.random((5, 3))
random_array_5

array([[0.95546832, 0.68291385, 0.05312869],
       [0.30885268, 0.59259469, 0.23512041],
       [0.964971  , 0.94504822, 0.84840088],
       [0.472324  , 0.84147671, 0.13111064],
       [0.30873366, 0.46299639, 0.7418472 ]])

## 3. Viewing arrays and matrices

In [22]:
np.unique(random_array_4)

array([0, 1, 3, 4, 5, 6, 8, 9])

In [23]:
a4 = np.random.randint(10, size=(2, 3, 4, 5))
a4

array([[[[3, 5, 8, 8, 7],
         [5, 0, 0, 2, 8],
         [9, 6, 4, 9, 7],
         [3, 3, 8, 3, 0]],

        [[1, 0, 0, 6, 7],
         [7, 9, 3, 0, 7],
         [7, 7, 0, 5, 4],
         [3, 1, 3, 1, 3]],

        [[4, 3, 1, 9, 5],
         [9, 1, 2, 3, 2],
         [2, 5, 7, 3, 0],
         [9, 9, 3, 4, 5]]],


       [[[3, 0, 4, 8, 6],
         [7, 2, 7, 3, 8],
         [6, 6, 5, 6, 5],
         [7, 1, 5, 4, 4]],

        [[9, 9, 0, 6, 2],
         [6, 8, 2, 4, 1],
         [6, 1, 5, 1, 6],
         [9, 8, 6, 5, 9]],

        [[7, 5, 4, 9, 6],
         [8, 1, 5, 5, 8],
         [3, 7, 7, 9, 4],
         [7, 5, 9, 6, 2]]]])

In [24]:
a4.shape, a4.ndim # 4 dimensional array demek ndim.

((2, 3, 4, 5), 4)

In [27]:
a1 = np.array([1, 2, 3])
ones = np.ones(3)
np.add(a1, ones)

array([2., 3., 4.])

In [28]:
a1 % 2

array([1, 0, 1], dtype=int32)

In [29]:
a1 / 2

array([0.5, 1. , 1.5])

In [30]:
np.exp(a1)

array([ 2.71828183,  7.3890561 , 20.08553692])

In [33]:
a1

array([1, 2, 3])

In [32]:
np.log(a1)

array([0.        , 0.69314718, 1.09861229])

## Aggregation
Aggregation = performing the same operation on a number of things

In [36]:
massive_array = np.random.random(100000)
massive_array


array([0.31828296, 0.913311  , 0.7571393 , ..., 0.78059249, 0.85200747,
       0.08640362])

## Dot product

In [38]:
np.random.seed(0)

mat1 = np.random.randint(10, size=(5, 3))
mat2 = np.random.randint(10, size=(5, 3))

mat1.shape, mat2.shape

((5, 3), (5, 3))

In [39]:
# Element-wise multiplication (Hadamard product)
mat1 * mat2

array([[30,  0, 21],
       [24,  7, 45],
       [27, 40, 18],
       [16, 21,  0],
       [24, 40,  0]])

In [40]:
# Transpose mat1
mat1.T

array([[5, 3, 3, 4, 8],
       [0, 7, 5, 7, 8],
       [3, 9, 2, 6, 1]])

In [41]:
mat1.shape, mat2.T.shape

((5, 3), (3, 5))

In [42]:
mat3 = np.dot(mat1, mat2.T)
mat3

array([[ 51,  55,  72,  20,  15],
       [130,  76, 164,  33,  44],
       [ 67,  39,  85,  27,  34],
       [115,  69, 146,  37,  47],
       [111,  77, 145,  56,  64]])

## Dot product exmaple (nut butter sales)

In [43]:
np.random.seed(0)
# Number of jars sold
sales_amounts = np.random.randint(20, size=(5,3))
sales_amounts

array([[12, 15,  0],
       [ 3,  3,  7],
       [ 9, 19, 18],
       [ 4,  6, 12],
       [ 1,  6,  7]])

In [44]:
# Create weekly_sales DataFrame
weekly_sales = pd.DataFrame(sales_amounts,
                            index=["Mon", "Tues", "Wed", "Thurs", "Fri"],
                            columns=["Almond butter", "Peanut butter", "Cashew butter"])
weekly_sales

Almond butter  Peanut butter  Cashew butter
Mon               12             15              0
Tues               3              3              7
Wed                9             19             18
Thurs              4              6             12
Fri                1              6              7

In [45]:
# Create prices array
prices = np.array([10, 8, 12])
prices

array([10,  8, 12])

In [46]:
prices.shape

(3,)

In [47]:
# Create butter_prices DataFrame
butter_prices = pd.DataFrame(prices.reshape(1, 3),
                             index=["Price"],
                             columns=["Almond butter", "Peanut butter", "Cashew butter"])
butter_prices

Almond butter  Peanut butter  Cashew butter
Price             10              8             12

In [48]:
sales_amounts.shape

(5, 3)

In [50]:
daily_sales = butter_prices.dot(weekly_sales.T)
daily_sales.shape

(1, 5)

In [51]:
weekly_sales

Almond butter  Peanut butter  Cashew butter
Mon               12             15              0
Tues               3              3              7
Wed                9             19             18
Thurs              4              6             12
Fri                1              6              7

In [52]:
weekly_sales["Total ($)"] = daily_sales.T
weekly_sales

Almond butter  Peanut butter  Cashew butter  Total ($)
Mon               12             15              0        240
Tues               3              3              7        138
Wed                9             19             18        458
Thurs              4              6             12        232
Fri                1              6              7        142

In [55]:
daily_sales.T

Price
Mon      240
Tues     138
Wed      458
Thurs    232
Fri      142

In [54]:
daily_sales

Mon  Tues  Wed  Thurs  Fri
Price  240   138  458    232  142

## 5. Sorting arrays

In [56]:
random_array = np.random.randint(10, size=(3, 5))
random_array

array([[7, 8, 1, 5, 9],
       [8, 9, 4, 3, 0],
       [3, 5, 0, 2, 3]])

In [57]:
np.sort(random_array)

array([[1, 5, 7, 8, 9],
       [0, 3, 4, 8, 9],
       [0, 2, 3, 3, 5]])

In [58]:
random_array

array([[7, 8, 1, 5, 9],
       [8, 9, 4, 3, 0],
       [3, 5, 0, 2, 3]])

In [59]:
np.argsort(random_array) # sort ve indexin birleşimi

array([[2, 3, 0, 1, 4],
       [4, 3, 2, 0, 1],
       [2, 3, 0, 4, 1]], dtype=int64)

In [60]:
random_array

array([[7, 8, 1, 5, 9],
       [8, 9, 4, 3, 0],
       [3, 5, 0, 2, 3]])

In [61]:
np.argmax(random_array, axis=0)

array([1, 1, 1, 0, 0], dtype=int64)

In [62]:
np.argmax(random_array, axis=1)

array([4, 1, 1], dtype=int64)

## 6. Practical Example - NumPy in Action!!!!

In [67]:
# Turn an image into a NumPy array
from matplotlib.image import imread

panda = imread("images/panda.png")
print(type(panda))

<class 'numpy.ndarray'>


In [68]:
car = imread("images/car-photo.png")
print(type(car))

<class 'numpy.ndarray'>


In [69]:
car[:1]

array([[[0.5019608 , 0.50980395, 0.4862745 , 1.        ],
        [0.3372549 , 0.34509805, 0.30588236, 1.        ],
        [0.20392157, 0.21568628, 0.14901961, 1.        ],
        ...,
        [0.64705884, 0.7058824 , 0.54901963, 1.        ],
        [0.59607846, 0.63529414, 0.45882353, 1.        ],
        [0.44705883, 0.47058824, 0.3372549 , 1.        ]]], dtype=float32)

In [70]:
dog = imread("images/dog-photo.png")
print(type(dog))

<class 'numpy.ndarray'>


In [71]:
dog

array([[[0.70980394, 0.80784315, 0.88235295, 1.        ],
        [0.72156864, 0.8117647 , 0.8862745 , 1.        ],
        [0.7411765 , 0.8156863 , 0.8862745 , 1.        ],
        ...,
        [0.49803922, 0.6862745 , 0.8392157 , 1.        ],
        [0.49411765, 0.68235296, 0.8392157 , 1.        ],
        [0.49411765, 0.68235296, 0.8352941 , 1.        ]],

       [[0.69411767, 0.8039216 , 0.8862745 , 1.        ],
        [0.7019608 , 0.8039216 , 0.88235295, 1.        ],
        [0.7058824 , 0.80784315, 0.88235295, 1.        ],
        ...,
        [0.5019608 , 0.6862745 , 0.84705883, 1.        ],
        [0.49411765, 0.68235296, 0.84313726, 1.        ],
        [0.49411765, 0.68235296, 0.8392157 , 1.        ]],

       [[0.6901961 , 0.8       , 0.88235295, 1.        ],
        [0.69803923, 0.8039216 , 0.88235295, 1.        ],
        [0.7058824 , 0.80784315, 0.88235295, 1.        ],
        ...,
        [0.5019608 , 0.6862745 , 0.84705883, 1.        ],
        [0.49803922, 0.686274

In [72]:
a1 = np.array([1, 2, 3])

a2 = np.array([[1, 2.0, 3.3],
               [4, 5, 6.5]])

a3 = np.array([[[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]],
               [[10, 11, 12],
                [13, 14, 15],
                [16, 17, 18]]])


In [73]:
a1[:2]

array([1, 2])

In [74]:
a2[:2]

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [78]:
a2[:,:2]

array([[1., 2.],
       [4., 5.]])

In [90]:
a3.shape

(2, 3, 3)

In [97]:
a3[:,:1]

array([[[ 1,  2,  3]],

       [[10, 11, 12]]])